homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52
  longitude: -0.26
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 44
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      automation

record:
  # Clear old data
  purge_days: 3

# View all events in a logbook
logbook:

# Track the sun
sun:

emulated_hue:

# Heating
nest:
  username: !secret nest_user
  password: !secret nest_pass

climate:
  platform: nest

# Weather Prediction
sensor:
  platform: yr

notify:
  name: Steve Phone
  platform: simplepush
  device_key: !secret simplepush

binary_sensor: !include sensor.yaml

light: !include light.yaml

automation: !include_dir_list automation

script: !include_dir_named scripts
