alias: Landing Motion
trigger:
  platform: state
  entity_id: binary_sensor.pir_landing
  to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.sun_up
    state: 'off'
  - condition: time
    after: '05:30:00'
    before: '23:30:00'
action:
  service: homeassistant.turn_on
  entity_id: light.landing
